# Locate BASISU.
# This module defines
# BASISU_TRANSCODER_LIBRARY
# BASISU_FOUND, if false, do not try to link to geos
# BASISU_INCLUDE_DIR, where to find the headers

#MESSAGE("Finding basis")

SET(CESIUM_NATIVE_DIR "" CACHE PATH "Root directory of cesium-native distribution")

FIND_PATH(CESIUM_NATIVE_INCLUDE_DIR CesiumUtility/Uri.h
  PATHS
    ${CESIUM_NATIVE_DIR}
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES include
)

FIND_LIBRARY(CESIUM_NATIVE_3DTILES_LIBRARY
  NAMES Cesium3DTiles
  PATHS  
    ${CESIUM_NATIVE_DIR}/lib
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_LIBRARY(CESIUM_NATIVE_3DTILES_SELECTION_LIBRARY
  NAMES Cesium3DTilesSelection
  PATHS  
    ${CESIUM_NATIVE_DIR}/lib
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_LIBRARY(CESIUM_NATIVE_GEOSPATIAL_LIBRARY
  NAMES CesiumGeospatial
  PATHS  
    ${CESIUM_NATIVE_DIR}/lib
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_LIBRARY(CESIUM_NATIVE_UTILITY_LIBRARY
  NAMES CesiumUtility
  PATHS  
    ${CESIUM_NATIVE_DIR}/lib
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_LIBRARY(CESIUM_NATIVE_ION_CLIENT_LIBRARY
  NAMES CesiumIonClient
  PATHS  
    ${CESIUM_NATIVE_DIR}/lib
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES lib64 lib
)

FIND_LIBRARY(CESIUM_NATIVE_GLTF_READER_LIBRARY
  NAMES CesiumGltfReader
  PATHS  
    ${CESIUM_NATIVE_DIR}/lib
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES lib64 lib
)

SET(CESIUM_NATIVE_FOUND "NO")
IF(CESIUM_NATIVE_3DTILES_LIBRARY AND
   CESIUM_NATIVE_3DTILES_SELECTION_LIBRARY AND
   CESIUM_NATIVE_GEOSPATIAL_LIBRARY AND
   CESIUM_NATIVE_UTILITY_LIBRARY AND
   CESIUM_NATIVE_ION_CLIENT_LIBRARY AND
   CESIUM_NATIVE_GLTF_READER_LIBRARY AND
   CESIUM_NATIVE_INCLUDE_DIR)
  SET(CESIUM_NATIVE_FOUND "YES")
ENDIF()

MESSAGE("Cesium native found ${CESIUM_NATIVE_FOUND}")
MESSAGE("CESIUM_NATIVE_INCLUDE_DIR ${CESIUM_NATIVE_INCLUDE_DIR}")
MESSAGE("CESIUM_NATIVE_3DTILES_LIBRARY ${CESIUM_NATIVE_3DTILES_LIBRARY}")

#MESSAGE("Basis found ${BASISU_FOUND}")
#MESSAGE("Basis include ${BASISU_INCLUDE_DIR}")
#MESSAGE("Basis transcoder ${BASISU_TRANSCODER_LIBRARY}")
