SET(CESIUM_NATIVE_DIR "" CACHE PATH "Root directory of cesium-native distribution")

FIND_PATH(CESIUM_NATIVE_INCLUDE_DIR CesiumUtility/Uri.h
  PATHS
    ${CESIUM_NATIVE_DIR}
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES include
)

MACRO( FIND_CESIUM_LIBRARY MYLIBRARY MYLIBRARYNAME )

FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        ${CESIUM_NATIVE_DIR}/lib
        $ENV{CESIUM_NATIVE_DIR}
        PATH_SUFFIXES lib64 lib
    NO_DEFAULT_PATH
     )

ENDMACRO(FIND_CESIUM_LIBRARY LIBRARY LIBRARYNAME)

FIND_CESIUM_LIBRARY(CESIUM_NATIVE_3DTILES_LIBRARY Cesium3DTiles)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_3DTILES_SELECTION_LIBRARY Cesium3DTilesSelection)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GEOSPATIAL_LIBRARY CesiumGeospatial)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_UTILITY_LIBRARY CesiumUtility)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_ION_CLIENT_LIBRARY CesiumIonClient)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GLTF_READER_LIBRARY CesiumGltfReader)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GEOMETRY_LIBRARY CesiumGeometry)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GLTF_LIBRARY CesiumGltf)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_KTX_READ_LIBRARY ktx_read)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_DRACO_LIBRARY draco)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_SPDLOG_LIBRARY spdlog)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_ASYNC++_LIBRARY async++)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_WEBPDECODER_LIBRARY webpdecoder)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_URIPARSER_LIBRARY uriparser)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_TURBOJPEG_LIBRARY turbojpeg)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_CSPRNG_LIBRARY csprng)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_MODPB64_LIBRARY modp_b64)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_JSONREADER_LIBRARY CesiumJsonReader)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_ASYNC_LIBRARY CesiumAsync)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_S2GEOMETRY_LIBRARY s2geometry)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_TINYXML2_LIBRARY tinyxml2)



SET(CESIUM_NATIVE_FOUND "NO")
IF(CESIUM_NATIVE_3DTILES_LIBRARY AND
   CESIUM_NATIVE_3DTILES_SELECTION_LIBRARY AND
   CESIUM_NATIVE_GEOSPATIAL_LIBRARY AND
   CESIUM_NATIVE_UTILITY_LIBRARY AND
   CESIUM_NATIVE_ION_CLIENT_LIBRARY AND
   CESIUM_NATIVE_GLTF_READER_LIBRARY AND
   CESIUM_NATIVE_GEOMETRY_LIBRARY AND
   CESIUM_NATIVE_GLTF_LIBRARY AND
   CESIUM_NATIVE_KTX_READ_LIBRARY AND
   CESIUM_NATIVE_DRACO_LIBRARY AND
   CESIUM_NATIVE_SPDLOG_LIBRARY AND
   CESIUM_NATIVE_ASYNC++_LIBRARY AND
   CESIUM_NATIVE_WEBPDECODER_LIBRARY AND
   CESIUM_NATIVE_URIPARSER_LIBRARY AND
   CESIUM_NATIVE_TURBOJPEG_LIBRARY AND
   CESIUM_NATIVE_CSPRNG_LIBRARY AND
   CESIUM_NATIVE_MODPB64_LIBRARY AND
   CESIUM_NATIVE_JSONREADER_LIBRARY AND
   CESIUM_NATIVE_ASYNC_LIBRARY AND
   CESIUM_NATIVE_S2GEOMETRY_LIBRARY AND
   CESIUM_NATIVE_TINYXML2_LIBRARY AND
   CESIUM_NATIVE_INCLUDE_DIR)
  SET(CESIUM_NATIVE_FOUND "YES")
ENDIF()