SET(CESIUM_NATIVE_DIR "" CACHE PATH "Root directory of cesium-native distribution")

FIND_PATH(CESIUM_NATIVE_INCLUDE_DIR CesiumUtility/Uri.h
  PATHS
    ${CESIUM_NATIVE_DIR}
    $ENV{CESIUM_NATIVE_DIR}
  PATH_SUFFIXES include
)

MACRO( FIND_CESIUM_LIBRARY MYLIBRARY MYLIBRARYNAME )

FIND_LIBRARY(${MYLIBRARY}_LIBRARY_DEBUG
    NAMES
        ${MYLIBRARYNAME}d
    PATHS
        ${CESIUM_NATIVE_DIR}/lib
        $ENV{CESIUM_NATIVE_DIR}
        PATH_SUFFIXES lib64 lib
    NO_DEFAULT_PATH
     )

FIND_LIBRARY(${MYLIBRARY}_LIBRARY_RELEASE
     NAMES
         ${MYLIBRARYNAME}
     PATHS
         ${CESIUM_NATIVE_DIR}/lib
         $ENV{CESIUM_NATIVE_DIR}
         PATH_SUFFIXES lib64 lib
     NO_DEFAULT_PATH
      )

select_library_configurations(${MYLIBRARY})

ENDMACRO(FIND_CESIUM_LIBRARY LIBRARY LIBRARYNAME)

FIND_CESIUM_LIBRARY(CESIUM_NATIVE_3DTILES Cesium3DTiles)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_3DTILES_SELECTION Cesium3DTilesSelection)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GEOSPATIAL CesiumGeospatial)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_UTILITY CesiumUtility)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_ION_CLIENT CesiumIonClient)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GLTF_READER CesiumGltfReader)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_3DTILES_READER Cesium3DTilesReader)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GEOMETRY CesiumGeometry)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GLTF CesiumGltf)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_KTX_READ ktx_read)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_DRACO draco)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_SPDLOG spdlog)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_ASYNC++ async++)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_WEBPDECODER webpdecoder)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_MESHOPTIMIZER meshoptimizer)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_URIPARSER uriparser)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_TURBOJPEG turbojpeg)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_CSPRNG csprng)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_MODPB64 modp_b64)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_JSONREADER CesiumJsonReader)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_ASYNC CesiumAsync)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_S2GEOMETRY s2geometry)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_RASTER_OVERLAYS CesiumRasterOverlays)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_3DTILES_CONTENT Cesium3DTilesContent)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_GLTF_CONTENT CesiumGltfContent)
FIND_CESIUM_LIBRARY(CESIUM_NATIVE_TINYXML2 tinyxml2)



SET(CESIUM_NATIVE_FOUND "NO")
IF(CESIUM_NATIVE_3DTILES_LIBRARY AND
   CESIUM_NATIVE_3DTILES_SELECTION_LIBRARY AND
   CESIUM_NATIVE_GEOSPATIAL_LIBRARY AND
   CESIUM_NATIVE_UTILITY_LIBRARY AND
   CESIUM_NATIVE_ION_CLIENT_LIBRARY AND
   CESIUM_NATIVE_GLTF_READER_LIBRARY AND
   CESIUM_NATIVE_3DTILES_READER_LIBRARY AND
   CESIUM_NATIVE_GEOMETRY_LIBRARY AND
   CESIUM_NATIVE_GLTF_LIBRARY AND
   CESIUM_NATIVE_KTX_READ_LIBRARY AND
   CESIUM_NATIVE_DRACO_LIBRARY AND
   CESIUM_NATIVE_SPDLOG_LIBRARY AND
   CESIUM_NATIVE_ASYNC++_LIBRARY AND
   CESIUM_NATIVE_WEBPDECODER_LIBRARY AND
   CESIUM_NATIVE_MESHOPTIMIZER_LIBRARY AND
   CESIUM_NATIVE_URIPARSER_LIBRARY AND
   CESIUM_NATIVE_TURBOJPEG_LIBRARY AND
   CESIUM_NATIVE_CSPRNG_LIBRARY AND
   CESIUM_NATIVE_MODPB64_LIBRARY AND
   CESIUM_NATIVE_JSONREADER_LIBRARY AND
   CESIUM_NATIVE_ASYNC_LIBRARY AND
   CESIUM_NATIVE_S2GEOMETRY_LIBRARY AND
   CESIUM_NATIVE_TINYXML2_LIBRARY AND
   CESIUM_NATIVE_RASTER_OVERLAYS_LIBRARY AND
   CESIUM_NATIVE_3DTILES_CONTENT_LIBRARY AND
   CESIUM_NATIVE_GLTF_CONTENT_LIBRARY AND
   CESIUM_NATIVE_INCLUDE_DIR)
  SET(CESIUM_NATIVE_FOUND "YES")
ENDIF()