version: 1.0.{build}
shallow_clone: true
os: Visual Studio 2017

install:
  #- cd C:\tools\vcpkg
  #- vcpkg install osg:x64-windows sqlite3:x64-windows protobuf:x64-windows poco:x64-windows
  #- vcpkg integrate install
  - mkdir c:\temp
  - cd c:\temp
  - ps: Start-FileDownload 'https://s3.amazonaws.com/pelican-public/osgearth-vcpkg-deps.7z'
  - 7z x osgearth-vcpkg-deps.7Z
  - cd C:\projects\osgearth

build_script:
  - mkdir build
  - cd build
  #- cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DWIN32_USE_MP=ON -DCMAKE_INSTALL_PREFIX=c:\projects\osgearth\install -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DWIN32_USE_MP=ON -DCMAKE_INSTALL_PREFIX=c:\projects\osgearth\install -DCMAKE_TOOLCHAIN_FILE=c:/temp/osgearth-vcpkg-deps/scripts/buildsystems/vcpkg.cmake
  - cmake --build . --target INSTALL --config Release
  - cd ..\install
  - 7z a c:\projects\osgearth\osgearth.zip .

cache: c:\tools\vcpkg\installed\

artifacts:
  - path: osgearth.zip
    name: osgearth

notifications:
  - provider: Slack
    incoming_webhook:
      secure: CeOwsQhxU4rvSp7EJrBWYhhfAhTFRMH/RxKYr2PBrAi3vk5hbMJBBYtvPAGtHMXp7k1E0JwbeC3rrtpVtg6wqbpplVMDSQZs+26H/LSY2so=



