// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector_tile.proto

#ifndef PROTOBUF_vector_5ftile_2eproto__INCLUDED
#define PROTOBUF_vector_5ftile_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace mapnik {
namespace vector {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_vector_5ftile_2eproto();
void protobuf_AssignDesc_vector_5ftile_2eproto();
void protobuf_ShutdownFile_vector_5ftile_2eproto();

class tile;
class tile_value;
class tile_feature;
class tile_layer;

enum tile_GeomType {
  tile_GeomType_Unknown = 0,
  tile_GeomType_Point = 1,
  tile_GeomType_LineString = 2,
  tile_GeomType_Polygon = 3
};
bool tile_GeomType_IsValid(int value);
const tile_GeomType tile_GeomType_GeomType_MIN = tile_GeomType_Unknown;
const tile_GeomType tile_GeomType_GeomType_MAX = tile_GeomType_Polygon;
const int tile_GeomType_GeomType_ARRAYSIZE = tile_GeomType_GeomType_MAX + 1;

// ===================================================================

class tile_value : public ::google::protobuf::MessageLite {
 public:
  tile_value();
  virtual ~tile_value();

  tile_value(const tile_value& from);

  inline tile_value& operator=(const tile_value& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const tile_value& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const tile_value* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(tile_value* other);

  // implements Message ----------------------------------------------

  tile_value* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const tile_value& from);
  void MergeFrom(const tile_value& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string string_value = 1;
  inline bool has_string_value() const;
  inline void clear_string_value();
  static const int kStringValueFieldNumber = 1;
  inline const ::std::string& string_value() const;
  inline void set_string_value(const ::std::string& value);
  inline void set_string_value(const char* value);
  inline void set_string_value(const char* value, size_t size);
  inline ::std::string* mutable_string_value();
  inline ::std::string* release_string_value();
  inline void set_allocated_string_value(::std::string* string_value);

  // optional float float_value = 2;
  inline bool has_float_value() const;
  inline void clear_float_value();
  static const int kFloatValueFieldNumber = 2;
  inline float float_value() const;
  inline void set_float_value(float value);

  // optional double double_value = 3;
  inline bool has_double_value() const;
  inline void clear_double_value();
  static const int kDoubleValueFieldNumber = 3;
  inline double double_value() const;
  inline void set_double_value(double value);

  // optional int64 int_value = 4;
  inline bool has_int_value() const;
  inline void clear_int_value();
  static const int kIntValueFieldNumber = 4;
  inline ::google::protobuf::int64 int_value() const;
  inline void set_int_value(::google::protobuf::int64 value);

  // optional uint64 uint_value = 5;
  inline bool has_uint_value() const;
  inline void clear_uint_value();
  static const int kUintValueFieldNumber = 5;
  inline ::google::protobuf::uint64 uint_value() const;
  inline void set_uint_value(::google::protobuf::uint64 value);

  // optional sint64 sint_value = 6;
  inline bool has_sint_value() const;
  inline void clear_sint_value();
  static const int kSintValueFieldNumber = 6;
  inline ::google::protobuf::int64 sint_value() const;
  inline void set_sint_value(::google::protobuf::int64 value);

  // optional bool bool_value = 7;
  inline bool has_bool_value() const;
  inline void clear_bool_value();
  static const int kBoolValueFieldNumber = 7;
  inline bool bool_value() const;
  inline void set_bool_value(bool value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(tile_value)
  // @@protoc_insertion_point(class_scope:mapnik.vector.tile.value)
 private:
  inline void set_has_string_value();
  inline void clear_has_string_value();
  inline void set_has_float_value();
  inline void clear_has_float_value();
  inline void set_has_double_value();
  inline void clear_has_double_value();
  inline void set_has_int_value();
  inline void clear_has_int_value();
  inline void set_has_uint_value();
  inline void clear_has_uint_value();
  inline void set_has_sint_value();
  inline void clear_has_sint_value();
  inline void set_has_bool_value();
  inline void clear_has_bool_value();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* string_value_;
  double double_value_;
  ::google::protobuf::int64 int_value_;
  float float_value_;
  bool bool_value_;
  ::google::protobuf::uint64 uint_value_;
  ::google::protobuf::int64 sint_value_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_vector_5ftile_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_vector_5ftile_2eproto();
  #endif
  friend void protobuf_AssignDesc_vector_5ftile_2eproto();
  friend void protobuf_ShutdownFile_vector_5ftile_2eproto();

  void InitAsDefaultInstance();
  static tile_value* default_instance_;
};
// -------------------------------------------------------------------

class tile_feature : public ::google::protobuf::MessageLite {
 public:
  tile_feature();
  virtual ~tile_feature();

  tile_feature(const tile_feature& from);

  inline tile_feature& operator=(const tile_feature& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const tile_feature& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const tile_feature* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(tile_feature* other);

  // implements Message ----------------------------------------------

  tile_feature* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const tile_feature& from);
  void MergeFrom(const tile_feature& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // repeated uint32 tags = 2 [packed = true];
  inline int tags_size() const;
  inline void clear_tags();
  static const int kTagsFieldNumber = 2;
  inline ::google::protobuf::uint32 tags(int index) const;
  inline void set_tags(int index, ::google::protobuf::uint32 value);
  inline void add_tags(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      tags() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_tags();

  // optional .mapnik.vector.tile.GeomType type = 3 [default = Unknown];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::mapnik::vector::tile_GeomType type() const;
  inline void set_type(::mapnik::vector::tile_GeomType value);

  // repeated uint32 geometry = 4 [packed = true];
  inline int geometry_size() const;
  inline void clear_geometry();
  static const int kGeometryFieldNumber = 4;
  inline ::google::protobuf::uint32 geometry(int index) const;
  inline void set_geometry(int index, ::google::protobuf::uint32 value);
  inline void add_geometry(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      geometry() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_geometry();

  // @@protoc_insertion_point(class_scope:mapnik.vector.tile.feature)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > tags_;
  mutable int _tags_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > geometry_;
  mutable int _geometry_cached_byte_size_;
  int type_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_vector_5ftile_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_vector_5ftile_2eproto();
  #endif
  friend void protobuf_AssignDesc_vector_5ftile_2eproto();
  friend void protobuf_ShutdownFile_vector_5ftile_2eproto();

  void InitAsDefaultInstance();
  static tile_feature* default_instance_;
};
// -------------------------------------------------------------------

class tile_layer : public ::google::protobuf::MessageLite {
 public:
  tile_layer();
  virtual ~tile_layer();

  tile_layer(const tile_layer& from);

  inline tile_layer& operator=(const tile_layer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const tile_layer& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const tile_layer* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(tile_layer* other);

  // implements Message ----------------------------------------------

  tile_layer* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const tile_layer& from);
  void MergeFrom(const tile_layer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 version = 15 [default = 1];
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 15;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated .mapnik.vector.tile.feature features = 2;
  inline int features_size() const;
  inline void clear_features();
  static const int kFeaturesFieldNumber = 2;
  inline const ::mapnik::vector::tile_feature& features(int index) const;
  inline ::mapnik::vector::tile_feature* mutable_features(int index);
  inline ::mapnik::vector::tile_feature* add_features();
  inline const ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_feature >&
      features() const;
  inline ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_feature >*
      mutable_features();

  // repeated string keys = 3;
  inline int keys_size() const;
  inline void clear_keys();
  static const int kKeysFieldNumber = 3;
  inline const ::std::string& keys(int index) const;
  inline ::std::string* mutable_keys(int index);
  inline void set_keys(int index, const ::std::string& value);
  inline void set_keys(int index, const char* value);
  inline void set_keys(int index, const char* value, size_t size);
  inline ::std::string* add_keys();
  inline void add_keys(const ::std::string& value);
  inline void add_keys(const char* value);
  inline void add_keys(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& keys() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_keys();

  // repeated .mapnik.vector.tile.value values = 4;
  inline int values_size() const;
  inline void clear_values();
  static const int kValuesFieldNumber = 4;
  inline const ::mapnik::vector::tile_value& values(int index) const;
  inline ::mapnik::vector::tile_value* mutable_values(int index);
  inline ::mapnik::vector::tile_value* add_values();
  inline const ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_value >&
      values() const;
  inline ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_value >*
      mutable_values();

  // optional uint32 extent = 5 [default = 4096];
  inline bool has_extent() const;
  inline void clear_extent();
  static const int kExtentFieldNumber = 5;
  inline ::google::protobuf::uint32 extent() const;
  inline void set_extent(::google::protobuf::uint32 value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(tile_layer)
  // @@protoc_insertion_point(class_scope:mapnik.vector.tile.layer)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_extent();
  inline void clear_has_extent();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_feature > features_;
  ::google::protobuf::uint32 version_;
  ::google::protobuf::uint32 extent_;
  ::google::protobuf::RepeatedPtrField< ::std::string> keys_;
  ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_value > values_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_vector_5ftile_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_vector_5ftile_2eproto();
  #endif
  friend void protobuf_AssignDesc_vector_5ftile_2eproto();
  friend void protobuf_ShutdownFile_vector_5ftile_2eproto();

  void InitAsDefaultInstance();
  static tile_layer* default_instance_;
};
// -------------------------------------------------------------------

class tile : public ::google::protobuf::MessageLite {
 public:
  tile();
  virtual ~tile();

  tile(const tile& from);

  inline tile& operator=(const tile& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const tile& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const tile* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(tile* other);

  // implements Message ----------------------------------------------

  tile* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const tile& from);
  void MergeFrom(const tile& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef tile_value value;
  typedef tile_feature feature;
  typedef tile_layer layer;

  typedef tile_GeomType GeomType;
  static const GeomType Unknown = tile_GeomType_Unknown;
  static const GeomType Point = tile_GeomType_Point;
  static const GeomType LineString = tile_GeomType_LineString;
  static const GeomType Polygon = tile_GeomType_Polygon;
  static inline bool GeomType_IsValid(int value) {
    return tile_GeomType_IsValid(value);
  }
  static const GeomType GeomType_MIN =
    tile_GeomType_GeomType_MIN;
  static const GeomType GeomType_MAX =
    tile_GeomType_GeomType_MAX;
  static const int GeomType_ARRAYSIZE =
    tile_GeomType_GeomType_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // repeated .mapnik.vector.tile.layer layers = 3;
  inline int layers_size() const;
  inline void clear_layers();
  static const int kLayersFieldNumber = 3;
  inline const ::mapnik::vector::tile_layer& layers(int index) const;
  inline ::mapnik::vector::tile_layer* mutable_layers(int index);
  inline ::mapnik::vector::tile_layer* add_layers();
  inline const ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_layer >&
      layers() const;
  inline ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_layer >*
      mutable_layers();

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(tile)
  // @@protoc_insertion_point(class_scope:mapnik.vector.tile)
 private:

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_layer > layers_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_vector_5ftile_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_vector_5ftile_2eproto();
  #endif
  friend void protobuf_AssignDesc_vector_5ftile_2eproto();
  friend void protobuf_ShutdownFile_vector_5ftile_2eproto();

  void InitAsDefaultInstance();
  static tile* default_instance_;
};
// ===================================================================


// ===================================================================

// tile_value

// optional string string_value = 1;
inline bool tile_value::has_string_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tile_value::set_has_string_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tile_value::clear_has_string_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tile_value::clear_string_value() {
  if (string_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_->clear();
  }
  clear_has_string_value();
}
inline const ::std::string& tile_value::string_value() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.value.string_value)
  return *string_value_;
}
inline void tile_value::set_string_value(const ::std::string& value) {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(value);
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.value.string_value)
}
inline void tile_value::set_string_value(const char* value) {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(value);
  // @@protoc_insertion_point(field_set_char:mapnik.vector.tile.value.string_value)
}
inline void tile_value::set_string_value(const char* value, size_t size) {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  string_value_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mapnik.vector.tile.value.string_value)
}
inline ::std::string* tile_value::mutable_string_value() {
  set_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    string_value_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mapnik.vector.tile.value.string_value)
  return string_value_;
}
inline ::std::string* tile_value::release_string_value() {
  clear_has_string_value();
  if (string_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = string_value_;
    string_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void tile_value::set_allocated_string_value(::std::string* string_value) {
  if (string_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete string_value_;
  }
  if (string_value) {
    set_has_string_value();
    string_value_ = string_value;
  } else {
    clear_has_string_value();
    string_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mapnik.vector.tile.value.string_value)
}

// optional float float_value = 2;
inline bool tile_value::has_float_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tile_value::set_has_float_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tile_value::clear_has_float_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tile_value::clear_float_value() {
  float_value_ = 0;
  clear_has_float_value();
}
inline float tile_value::float_value() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.value.float_value)
  return float_value_;
}
inline void tile_value::set_float_value(float value) {
  set_has_float_value();
  float_value_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.value.float_value)
}

// optional double double_value = 3;
inline bool tile_value::has_double_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void tile_value::set_has_double_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void tile_value::clear_has_double_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void tile_value::clear_double_value() {
  double_value_ = 0;
  clear_has_double_value();
}
inline double tile_value::double_value() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.value.double_value)
  return double_value_;
}
inline void tile_value::set_double_value(double value) {
  set_has_double_value();
  double_value_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.value.double_value)
}

// optional int64 int_value = 4;
inline bool tile_value::has_int_value() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void tile_value::set_has_int_value() {
  _has_bits_[0] |= 0x00000008u;
}
inline void tile_value::clear_has_int_value() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void tile_value::clear_int_value() {
  int_value_ = GOOGLE_LONGLONG(0);
  clear_has_int_value();
}
inline ::google::protobuf::int64 tile_value::int_value() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.value.int_value)
  return int_value_;
}
inline void tile_value::set_int_value(::google::protobuf::int64 value) {
  set_has_int_value();
  int_value_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.value.int_value)
}

// optional uint64 uint_value = 5;
inline bool tile_value::has_uint_value() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void tile_value::set_has_uint_value() {
  _has_bits_[0] |= 0x00000010u;
}
inline void tile_value::clear_has_uint_value() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void tile_value::clear_uint_value() {
  uint_value_ = GOOGLE_ULONGLONG(0);
  clear_has_uint_value();
}
inline ::google::protobuf::uint64 tile_value::uint_value() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.value.uint_value)
  return uint_value_;
}
inline void tile_value::set_uint_value(::google::protobuf::uint64 value) {
  set_has_uint_value();
  uint_value_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.value.uint_value)
}

// optional sint64 sint_value = 6;
inline bool tile_value::has_sint_value() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void tile_value::set_has_sint_value() {
  _has_bits_[0] |= 0x00000020u;
}
inline void tile_value::clear_has_sint_value() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void tile_value::clear_sint_value() {
  sint_value_ = GOOGLE_LONGLONG(0);
  clear_has_sint_value();
}
inline ::google::protobuf::int64 tile_value::sint_value() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.value.sint_value)
  return sint_value_;
}
inline void tile_value::set_sint_value(::google::protobuf::int64 value) {
  set_has_sint_value();
  sint_value_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.value.sint_value)
}

// optional bool bool_value = 7;
inline bool tile_value::has_bool_value() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void tile_value::set_has_bool_value() {
  _has_bits_[0] |= 0x00000040u;
}
inline void tile_value::clear_has_bool_value() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void tile_value::clear_bool_value() {
  bool_value_ = false;
  clear_has_bool_value();
}
inline bool tile_value::bool_value() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.value.bool_value)
  return bool_value_;
}
inline void tile_value::set_bool_value(bool value) {
  set_has_bool_value();
  bool_value_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.value.bool_value)
}

// -------------------------------------------------------------------

// tile_feature

// optional uint64 id = 1;
inline bool tile_feature::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tile_feature::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tile_feature::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tile_feature::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 tile_feature::id() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.feature.id)
  return id_;
}
inline void tile_feature::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.feature.id)
}

// repeated uint32 tags = 2 [packed = true];
inline int tile_feature::tags_size() const {
  return tags_.size();
}
inline void tile_feature::clear_tags() {
  tags_.Clear();
}
inline ::google::protobuf::uint32 tile_feature::tags(int index) const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.feature.tags)
  return tags_.Get(index);
}
inline void tile_feature::set_tags(int index, ::google::protobuf::uint32 value) {
  tags_.Set(index, value);
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.feature.tags)
}
inline void tile_feature::add_tags(::google::protobuf::uint32 value) {
  tags_.Add(value);
  // @@protoc_insertion_point(field_add:mapnik.vector.tile.feature.tags)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
tile_feature::tags() const {
  // @@protoc_insertion_point(field_list:mapnik.vector.tile.feature.tags)
  return tags_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
tile_feature::mutable_tags() {
  // @@protoc_insertion_point(field_mutable_list:mapnik.vector.tile.feature.tags)
  return &tags_;
}

// optional .mapnik.vector.tile.GeomType type = 3 [default = Unknown];
inline bool tile_feature::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void tile_feature::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void tile_feature::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void tile_feature::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::mapnik::vector::tile_GeomType tile_feature::type() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.feature.type)
  return static_cast< ::mapnik::vector::tile_GeomType >(type_);
}
inline void tile_feature::set_type(::mapnik::vector::tile_GeomType value) {
  assert(::mapnik::vector::tile_GeomType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.feature.type)
}

// repeated uint32 geometry = 4 [packed = true];
inline int tile_feature::geometry_size() const {
  return geometry_.size();
}
inline void tile_feature::clear_geometry() {
  geometry_.Clear();
}
inline ::google::protobuf::uint32 tile_feature::geometry(int index) const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.feature.geometry)
  return geometry_.Get(index);
}
inline void tile_feature::set_geometry(int index, ::google::protobuf::uint32 value) {
  geometry_.Set(index, value);
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.feature.geometry)
}
inline void tile_feature::add_geometry(::google::protobuf::uint32 value) {
  geometry_.Add(value);
  // @@protoc_insertion_point(field_add:mapnik.vector.tile.feature.geometry)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
tile_feature::geometry() const {
  // @@protoc_insertion_point(field_list:mapnik.vector.tile.feature.geometry)
  return geometry_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
tile_feature::mutable_geometry() {
  // @@protoc_insertion_point(field_mutable_list:mapnik.vector.tile.feature.geometry)
  return &geometry_;
}

// -------------------------------------------------------------------

// tile_layer

// required uint32 version = 15 [default = 1];
inline bool tile_layer::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tile_layer::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tile_layer::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tile_layer::clear_version() {
  version_ = 1u;
  clear_has_version();
}
inline ::google::protobuf::uint32 tile_layer::version() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.layer.version)
  return version_;
}
inline void tile_layer::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.layer.version)
}

// required string name = 1;
inline bool tile_layer::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tile_layer::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tile_layer::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tile_layer::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& tile_layer::name() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.layer.name)
  return *name_;
}
inline void tile_layer::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.layer.name)
}
inline void tile_layer::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:mapnik.vector.tile.layer.name)
}
inline void tile_layer::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mapnik.vector.tile.layer.name)
}
inline ::std::string* tile_layer::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mapnik.vector.tile.layer.name)
  return name_;
}
inline ::std::string* tile_layer::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void tile_layer::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mapnik.vector.tile.layer.name)
}

// repeated .mapnik.vector.tile.feature features = 2;
inline int tile_layer::features_size() const {
  return features_.size();
}
inline void tile_layer::clear_features() {
  features_.Clear();
}
inline const ::mapnik::vector::tile_feature& tile_layer::features(int index) const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.layer.features)
  return features_.Get(index);
}
inline ::mapnik::vector::tile_feature* tile_layer::mutable_features(int index) {
  // @@protoc_insertion_point(field_mutable:mapnik.vector.tile.layer.features)
  return features_.Mutable(index);
}
inline ::mapnik::vector::tile_feature* tile_layer::add_features() {
  // @@protoc_insertion_point(field_add:mapnik.vector.tile.layer.features)
  return features_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_feature >&
tile_layer::features() const {
  // @@protoc_insertion_point(field_list:mapnik.vector.tile.layer.features)
  return features_;
}
inline ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_feature >*
tile_layer::mutable_features() {
  // @@protoc_insertion_point(field_mutable_list:mapnik.vector.tile.layer.features)
  return &features_;
}

// repeated string keys = 3;
inline int tile_layer::keys_size() const {
  return keys_.size();
}
inline void tile_layer::clear_keys() {
  keys_.Clear();
}
inline const ::std::string& tile_layer::keys(int index) const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.layer.keys)
  return keys_.Get(index);
}
inline ::std::string* tile_layer::mutable_keys(int index) {
  // @@protoc_insertion_point(field_mutable:mapnik.vector.tile.layer.keys)
  return keys_.Mutable(index);
}
inline void tile_layer::set_keys(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.layer.keys)
  keys_.Mutable(index)->assign(value);
}
inline void tile_layer::set_keys(int index, const char* value) {
  keys_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:mapnik.vector.tile.layer.keys)
}
inline void tile_layer::set_keys(int index, const char* value, size_t size) {
  keys_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mapnik.vector.tile.layer.keys)
}
inline ::std::string* tile_layer::add_keys() {
  return keys_.Add();
}
inline void tile_layer::add_keys(const ::std::string& value) {
  keys_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:mapnik.vector.tile.layer.keys)
}
inline void tile_layer::add_keys(const char* value) {
  keys_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:mapnik.vector.tile.layer.keys)
}
inline void tile_layer::add_keys(const char* value, size_t size) {
  keys_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:mapnik.vector.tile.layer.keys)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
tile_layer::keys() const {
  // @@protoc_insertion_point(field_list:mapnik.vector.tile.layer.keys)
  return keys_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
tile_layer::mutable_keys() {
  // @@protoc_insertion_point(field_mutable_list:mapnik.vector.tile.layer.keys)
  return &keys_;
}

// repeated .mapnik.vector.tile.value values = 4;
inline int tile_layer::values_size() const {
  return values_.size();
}
inline void tile_layer::clear_values() {
  values_.Clear();
}
inline const ::mapnik::vector::tile_value& tile_layer::values(int index) const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.layer.values)
  return values_.Get(index);
}
inline ::mapnik::vector::tile_value* tile_layer::mutable_values(int index) {
  // @@protoc_insertion_point(field_mutable:mapnik.vector.tile.layer.values)
  return values_.Mutable(index);
}
inline ::mapnik::vector::tile_value* tile_layer::add_values() {
  // @@protoc_insertion_point(field_add:mapnik.vector.tile.layer.values)
  return values_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_value >&
tile_layer::values() const {
  // @@protoc_insertion_point(field_list:mapnik.vector.tile.layer.values)
  return values_;
}
inline ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_value >*
tile_layer::mutable_values() {
  // @@protoc_insertion_point(field_mutable_list:mapnik.vector.tile.layer.values)
  return &values_;
}

// optional uint32 extent = 5 [default = 4096];
inline bool tile_layer::has_extent() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void tile_layer::set_has_extent() {
  _has_bits_[0] |= 0x00000020u;
}
inline void tile_layer::clear_has_extent() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void tile_layer::clear_extent() {
  extent_ = 4096u;
  clear_has_extent();
}
inline ::google::protobuf::uint32 tile_layer::extent() const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.layer.extent)
  return extent_;
}
inline void tile_layer::set_extent(::google::protobuf::uint32 value) {
  set_has_extent();
  extent_ = value;
  // @@protoc_insertion_point(field_set:mapnik.vector.tile.layer.extent)
}

// -------------------------------------------------------------------

// tile

// repeated .mapnik.vector.tile.layer layers = 3;
inline int tile::layers_size() const {
  return layers_.size();
}
inline void tile::clear_layers() {
  layers_.Clear();
}
inline const ::mapnik::vector::tile_layer& tile::layers(int index) const {
  // @@protoc_insertion_point(field_get:mapnik.vector.tile.layers)
  return layers_.Get(index);
}
inline ::mapnik::vector::tile_layer* tile::mutable_layers(int index) {
  // @@protoc_insertion_point(field_mutable:mapnik.vector.tile.layers)
  return layers_.Mutable(index);
}
inline ::mapnik::vector::tile_layer* tile::add_layers() {
  // @@protoc_insertion_point(field_add:mapnik.vector.tile.layers)
  return layers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_layer >&
tile::layers() const {
  // @@protoc_insertion_point(field_list:mapnik.vector.tile.layers)
  return layers_;
}
inline ::google::protobuf::RepeatedPtrField< ::mapnik::vector::tile_layer >*
tile::mutable_layers() {
  // @@protoc_insertion_point(field_mutable_list:mapnik.vector.tile.layers)
  return &layers_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace vector
}  // namespace mapnik

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vector_5ftile_2eproto__INCLUDED
