// ***DO NOT EDIT THIS FILE - IT IS AUTOMATICALLY GENERATED BY CMAKE***

#include <osgEarthFeatures/Shaders>

namespace osgEarth { namespace Features
{
    Shaders::Shaders()
    {
        // none yet
    }
} }
