#version 400
#pragma vp_name "Flora tessellation control shader"

/**
 * TCS that distributes data based on a Land Use code sampler.
 */
 
#pragma vp_entryPoint "oe_landcover_configureTess"
#pragma vp_location   "tess_control"

layout(vertices=3) out;

uniform float oe_landcover_density;

// stage global: tile coordinates
vec4 oe_layer_tilec;

// declare the coverage acceptance function, generated by LandCoverBiome
int oe_landcover_getBiomeIndex(in vec4 coords);

flat out int oe_landcover_biomeIndex;


// MAIN ENTRY POINT                
void oe_landcover_configureTess()
{
	if (gl_InvocationID == 0)
	{
        float r0 = 1.0;

        oe_landcover_biomeIndex = oe_landcover_getBiomeIndex(oe_layer_tilec);
        if ( oe_landcover_biomeIndex >= 0 )
        {
            float d = oe_landcover_density * r0;

            gl_TessLevelOuter[0] = d;
            gl_TessLevelOuter[1] = d;
            gl_TessLevelOuter[2] = d;
            gl_TessLevelInner[0] = d;
        }
        else
        {
            gl_TessLevelOuter[0] = 0;
            gl_TessLevelOuter[1] = 0;
            gl_TessLevelOuter[2] = 0;
            gl_TessLevelInner[0] = 0;
        }
	}
}
